### PR TITLE
Add dockerfile

### LINKED ISSUE #341: Docker Image
Something similar was discussed in #35.

It would be convenient to have heedy available in a docker image that you can pull straight from docker hub. At least for people who already have a hosting setup heavily relying on docker, it would simplify adoption greatly.

I've never used makefiles myself, so I'm not clear on all the details yet, but it looks like it should be relatively simple.

- Use a multi-stage build
- The first stage build the frontend with the [node image](https://hub.docker.com/_/node)
- The second stage builds heedy with the [golang image](https://hub.docker.com/_/golang) with the frontend copied over
- The third stage should be some minimal image that only executes the image from stage 2

Automated builds on docker hub for all commits and/or tags are very easy to set up.

If this is something you'd see in the scope of this project, I'd be willing to give it a shot.

### PR DESCRIPTION
**Pull request by ShaddyDC**
So, I just gave it a shot, and I think it's working.

- You can build it locally with `sudo docker build -t heedy .`
- The created image can be executed with `sudo docker run --rm -it -p 1324:1324 heedy`
- To have a persistent database, you can use something like `sudo docker run --rm -it -p 1324:1324 -v "$PWD/tmp:/root/.local/share" heedy` , which allows heedy to save its data in a `tmp` folder in the current directory.

I have chosen the `alpine` base image as it is known for its small size. It is `30.9MB` on my machine, which seems reasonable. For it to work, I also needed to build the backend with the `golang:alpine` image. I haven't tested the api or any other functionality like that yet, but it seems to be working so far.

You can potentially speed up build times by excluding files and folders with a `.dockerignore`. Maybe you could also only copy folders as necessary into the build stages. I have tried to keep complexity to a minimum here. Especially if builds are usually done online once, and after you just pull the completed image, I'm not sure if the added complexity would be worth it here.

Feedback is appreciated, and I can change things as needed.

Fixes #341

### CODE REVIEW

**Comment by ShaddyDC** [comment]
I noticed that with persistent storage, it would often erroneously think it was already running. I removed the check altogether for now. I don't think that should be an issue in docker setups, unless you're trying to run multiple instances with different ports. If it's important, I can change it so the file is only removed when the process receives a SIGTERM or SIGINT, but I'm unsure how reliable that would be.

**Comment by dkumor** [comment]
Hi, docker is a great fit here, since otherwise heedy plugins could have access to the rest of the system, so I am really happy that you took the initiative to set it up!

I am not too experienced with docker in general, other than running a couple services, so I have a couple questions:
1) Why is the pid file not being removed on exit? It looks like heedy is started in the background with `./heedy`, so maybe running `./heedy stop /root/.local/share/heedy`, (or just sending SIGINT to the process in the pid file) would allow a clean exit? Heedy does cleanup on SIGINT - but closes immediately on SIGTERM.
2) Does the `alpine` image have Python>=3.7 and pip? Heedy by itself isn't particularly powerful,it only becomes really useful once the plugins are installed, which depend on Python.

Unfortunately, the currently release builds of plugins support alpha 1, but not heedy's master version, which is built here (and will become alpha 2 in a month or two) - I have attached builds of master for fitbit and notebook plugins (you can build them yourself too if you want).
[heedy-notebook-plugin-0.0.2-git.17.zip](https://github.com/heedy/heedy/files/5860731/heedy-notebook-plugin-0.0.2-git.17.zip)
[heedy-fitbit-plugin-0.0.1-git.20.zip](https://github.com/heedy/heedy/files/5860745/heedy-fitbit-plugin-0.0.1-git.20.zip)

I will be very happy to merge this, and definitely agree that simplicity is a big benefit here!

**Comment by ShaddyDC** [comment]
The python support is a good point. I'd completely forgotten about all the plugin stuff when just trying to get it to run. I've updated the Dockerfile to support it. There's still some issues remaining however.

1. I think SIGINT was transmitted to the process properly in my tests. It looks to me like the `heedy.pid` file is just not removed at all. I've searched for mentions of it in the source code, and it only shows up in the functions `writepid` and `writepid`, unless I'm missing something? I've also still found the file in my local test installation, although it could be I hadn't properly shut it down.
2. The way `StartProcess` works for updates / restarts is not ideal since it moves the process into the background. If you run it directly in a terminal, you can then not shut it down any more with ctrl+c. In docker, when the main process exits, it assumes the program terminated and shuts down the whole container. Currently, you have to restart it yourself with the extra arguments `--update`, which is not ideal. There's probably ways to work around it here, but it may be better to change it altogether. Alternatively, I guess you could just always run it with the `--update` option? Then a user would only have to restart it at all, which doesn't seem like a big problem.
3. Docker containers are ephemeral, and they should be stateless. Ideally, everything you need should be installed once during the image creation and then never be needed again. This doesn't work too well with the plugin system, unfortunately, unless you want to reinstall everything every boot. It's a bit unfortunate, but I think we may just need a different installation directory for python packages next to the other persistent data. Maybe this can be done by running pip with the `--target` option.

Besides all that, I got the notebook plugin installed and opened. It wasn't working quite right yet though, as I wasn't able to execute any code.  
It looks like it can't start the kernel, and the console gives the error `Exception: Jupyter command `jupyter-notebook` not found.`.

Looks like this whole thing is more complicated than I initially thought. :sweat_smile:

**Comment by dkumor** [comment]
1) So the PID file is checked on process startup, and if a process of that PID already exists, it gives the error. It might make sense that in docker, the process always has the same PID, so it detects its own PID! I will commit an update that removes the PID file on exit.
2) I will think about this - making the server not fully restart is doable, but might take a bit of code changes and debugging, since some code does use global state.
3) I was thinking of upgrading the python support to use poetry, which would create virtualenvs for each plugin, and would fix the issue of statelessness, since the environments (and all installed packages) would be in the heedy directory.

I think that once the above changes are made to heedy, it should work without issues in a container. The changes might take me a couple weeks (especially poetry support/no-restart), so I can either merge this now, or wait until I have fixes for the above before adding - which would you prefer?

**Comment by ShaddyDC** [comment]
I completely forgot virtualenvs were a thing. That sounds like a good idea!

I'd hold off on merging until it's actually functional, and I'm not completely sure no more debugging on this side will be required once the other parts are done. I'm in no hurry, so thank you for taking the time to take care of all this. 

Regarding a full restart, at least for this case, you could work around it with a start script that restarts with the update arguments based on an exit code or something along those lines, which would be a lot simpler to implement, but also less nice.

**Comment by ShaddyDC** [comment]
I remembered there's 2 things that will still need to be done before merging this later. I'll note them down so I don't forget them once it's time.

1. Remove the entrypoint that removes the pid file, and potentially replace it with [dumb-init](https://github.com/Yelp/dumb-init) if signals aren't processed properly.
2. The current base image is pretty big at around 900 MB iirc. The alpine image didn't seem to be working for installing packages, and I wanted to get it running first, but this can probably be improved.

**Comment by dkumor** [comment]
Thanks! I'll make sure to comment here once I have implemented fixes for the issues I mentioned!

**Comment by dkumor** [comment]
Heedy should now no longer have issues with the pid file, should no longer have issues doing restarts, and should install plugin dependencies in venvs within the heedy folder. Please note that the default configuration file changed - if you want to keep an existing database, remove all elements from pip_args in heedy.conf (since it is now run within a venv).

An updated version of the notebook plugin is needed to play nice with the venvs that are now created:
[heedy-notebook-plugin-0.0.2-git.19.zip](https://github.com/heedy/heedy/files/5869346/heedy-notebook-plugin-0.0.2-git.19.zip)

**Comment by ShaddyDC** [comment]
That was quick! I've tried running it, and the changes seem to be working great. Starting the kernel for the notebook still fails though, with 

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/root/.local/share/heedy/venvs/notebook/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 50629)
```

I can look into it on the weekend.

**Comment by ShaddyDC** [comment]
Okay, I found the issue. In the docker container, currently everything is run as root as that is the simplest to set up. However, Jupyter is generally not a fan of that. In the log was `[C 15:07:06.161 NotebookApp] Running as root is not recommended. Use --allow-root to bypass.`, but I figured it's just a warning you can ignore, but it turns out it actually just terminates.  
Adding `--allow-root` as an argument makes it work. 

One solution would be to just always pass it. Alternatively the container can be changed to always run its contents as a non-root user.  I've got such a version running locally, but it's a bit more effort to run it if you want to share folders on the host system due to permissions. On the other hand, it's arguably better practice.

Which one would you prefer?

**Comment by dkumor** [comment]
If you open an issue for this in https://github.com/heedy/heedy-notebook-plugin I will fix it this weekend - you can also do a PR, it should be as simple as adding `--allow-root` to the commands on https://github.com/heedy/heedy-notebook-plugin/blob/master/manager.py#L325

The notebook plugin should work even if heedy itself is run as root in a normal environment.

Thanks for taking the time to debug this!

**Comment by ShaddyDC** [comment]
I'll make a pull request in a bit. Should I make the docker image run as root or as a user though?

**Comment by dkumor** [comment]
Whichever you think is better - I am unfamiliar with best practices in the docker world. How are database folders usually shared? Are docker services usually run as root?

My intuition suggests running as a user might be best, but if setting up shared folder/running the container will be painful with non-root, then maybe leaving as root is best.

**Comment by ShaddyDC** [comment]
I think it's best practice to make it run as non-root, so I'll just go with that. It's probably fine. 

You can still run it normally with `docker run --rm -it -p 1324:1324 heedy`

You can run it with a local folder with something like `docker run --rm -it -p 1324:1324 -v $PWD/heedy/:/data --user $UID heedy`  
You only need to make sure that the current user has r/w access to that folder, or use the uid of a user who has. 

I'm not really experienced with using non-host volumes, so I can't guarantee those will work.

This version is working so far. All that's left to do is to reduce the image size by trying smaller base images. I'll get to that over the next couple of days.

**Comment by ShaddyDC** [comment]
I think I've done everything I wanted to do. It should be working too.

**Comment by dkumor** [comment]
Thanks a lot! Changes were merged!

**Comment by ShaddyDC** [comment]
Great! If it's not asking too much, it would be great if you could put it on [Docker Hub](https://hub.docker.com/) too. Then people can just put heedy's identifier somewhere and pull the built project instead of having to build it themselves.
It's also very easy to have it build new commits or tags automatically. 

Anyway, thank you for being so quick about everything and helping me out where needed. :)

**Comment by dkumor** [comment]
I will put it on dockerhub in a couple weeks, once I am finalizing 0.4 - there is one more incompatible database schema change upcoming - and there won't be an automated upgrade path (an upgrade would require manually adding a database table in sqlite), so I want to commit that changeset before release/distribution.

After 0.4 is released, further database changes should have a clean/built in upgrade path, so that's the best time to put it up. I will comment here once it is released!

**Pull request merged**
